/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InformateIndexRouteImport } from './routes/informate.index'
import { Route as InformateTemaRouteImport } from './routes/informate.$tema'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InformateIndexRoute = InformateIndexRouteImport.update({
  id: '/informate/',
  path: '/informate/',
  getParentRoute: () => rootRouteImport,
} as any)
const InformateTemaRoute = InformateTemaRouteImport.update({
  id: '/informate/$tema',
  path: '/informate/$tema',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/informate/$tema': typeof InformateTemaRoute
  '/informate/': typeof InformateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/informate/$tema': typeof InformateTemaRoute
  '/informate': typeof InformateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/informate/$tema': typeof InformateTemaRoute
  '/informate/': typeof InformateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/informate/$tema' | '/informate/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/informate/$tema' | '/informate'
  id: '__root__' | '/' | '/informate/$tema' | '/informate/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InformateTemaRoute: typeof InformateTemaRoute
  InformateIndexRoute: typeof InformateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informate/': {
      id: '/informate/'
      path: '/informate'
      fullPath: '/informate/'
      preLoaderRoute: typeof InformateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informate/$tema': {
      id: '/informate/$tema'
      path: '/informate/$tema'
      fullPath: '/informate/$tema'
      preLoaderRoute: typeof InformateTemaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InformateTemaRoute: InformateTemaRoute,
  InformateIndexRoute: InformateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
